first_clone/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    #################post urls#########################
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    re_path('^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post_new'),
    re_path('^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    re_path('^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    re_path('^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

    ################comment urls######################
    re_path('^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path('^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path('^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

first_clone/first_clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('account/logout/', logout, name='logout', kwargs={'next_page':'/'}),
]

first_clone/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    #adding the publish date
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    #check for all approved comments
    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk':self.pk})



class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=30)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text[:10] + '...'

    def get_absolute_url(self):
        return reverse("blog:post_list")

first_clone/blog/forms.py
from django import forms
from blog.models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = {'author', 'title', 'text'}

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

    field_order = ['author', 'title', 'text']

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = {'author', 'text'}

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

first_clone/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
# Create your views here.


########################post class based views################################
class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm

    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm

    model = Post
    template_name = 'blog/post_update_form.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')



########################post functional views######################


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=post.pk)


########################comment views######################

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form':form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

first_clone/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>The company blog.</h1>
    <p>A place to express.</p>
  </div>

  <p>Your personal space to relax.</p>
{% endblock %}

first_clone/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>

    <!-- Bootstrap -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Medium Style Editor -->

    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->

    <link rel="stylesheet" href="{% static 'css\main.css' %}">

    <!-- Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

  </head>
  <body>

    <!-- Navbar -->

    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <ul class="nav nav-tabs">
          {% with url_name=request.resolver_match.url_name %}
          <li class="nav-item"><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog</a></li>
          <li class="nav-item"><a class="nav-link {% if url_name == 'about' %}active{% endif %}" href="{% url 'blog:about' %}">About</a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.github.com">Github</a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com">LinkedIn</a></li>
          {% endwith %}
        </ul>
        <ul class="nav nav-tabs navbar-right" role="tablist">
          {% if user.is_authenticated %}
          {% with url_name=request.resolver_match.url_name %}
           <li class="nav-item"><a class="nav-link {% if url_name == 'post_new' %}active{% endif %}" href="{% url 'blog:post_new' %}">Create</a></li>
          <li class="nav-item "><a class="nav-link {% if url_name == 'post_draft_list' %}active{% endif %}" href="{% url 'blog:post_draft_list' %}">Drafts</a></li>
          {% endwith %}
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
          <li class="nav-item nav-link">Hello, {{ user.username }}</li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>

      </div>
    </nav>

    <!-- CONTENT BLOCK -->

    <div class="content container my-5">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

first_clone/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block content %}

  <h1>Add comment</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="save btn btn-primary" type="submit" value="Post comment">
  </form>
  <script>
    var editor = new MediumEditor('.editable', {
      placeholder: false
  });
  </script>
{% endblock %}

first_clone/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}?</p>
    <input class="btn btn-danger" type="submit" value="Delete">
  </form>

{% endblock %}

first_clone/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="">
  <h1 class="posttitle display-3">{{ post.title }}</h1>
  {% if post.published_date %}
    <div class="date postdate">
      {{ post.published_date }}
    </div>
  {% else %}
  <div class="btn-wrapper">
    <a class="btn btn-primary btn-publish" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
  </div>
  {% endif %}

  <p class="postcontent">{{ post.text|safe|linebreaks }} </p>



  {% if user.is_authenticated %}
  <div class="justify-content-end">

    <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">Edit post</a>
    <a class="btn btn-warning" href="{% url 'blog:post_remove' pk=post.pk %}">Remove post</a>
    </div>

  {% endif %}


  </div>

  {% if post.published_date %}
  <br>
  <hr>
  <div class="btn-wrapper">
    <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
  </div>

  <hr>
  <br>
  <div class="container">
    {% for comment in post.comments.all %}

    {% if user.is_authenticated or comment.approved_comment %}
      {{ comment.created_date}}
      {% if not comment.approved_comment %}
          <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}">Remove comment</a>
          <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve comment</a>
      {% endif %}

      <p class="author-name">{{ comment.author }}:</p>
      <p>{{ comment.text|safe|linebreaks}}</p>

      <hr>
    {% endif %}
    {% empty %}
    <p>No comments.</p>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}

first_clone/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}

{% block content %}
  {% if posts %}
  {% for post in posts %}
    <div class="post">
      <p class="date">Created: {{ post.created_date|date:"d-m-Y"}}</p>
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    </div>
  {% endfor %}
  {% endif %}
{% endblock %}

first_clone/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block content %}

<h3 class="display-3 text-center">Create blog</h3>
<form class="post-form" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="btn btn-success save" type="submit" value="Create">
</form>

<script>
  var editor = new MediumEditor('.editable', {
    placeholder: false
});
</script>
{% endblock %}

first_clone/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}

  <div class="centerstage">
    {% for post in post_list %}
      <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <div class="date">
          <p>Published on: {{ post.published_date|date:"d M, Y" }}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
      </div>
      {% empty %}
      <p class="display-4 text-center">Nothing to show. {% if user.is_authenticated %}
      Create a blog <a class="" href="{% url 'blog:post_new' %}">here</a>. {% else %}
      <a class="" href="{% url 'login' %}">Login</a> and publish your own blog!
      {% endif %}</p>
    {% endfor %}
  </div>

{% endblock %}

first_clone/blog/templates/blog/post_update_form.html
{% extends "blog/base.html" %}

{% block content %}

<h3 class="display-3 text-center">Edit blog</h3>
<form class="post-form" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="btn btn-success save" type="submit" value="Save">
</form>

<script>
  var editor = new MediumEditor('.editable');
</script>
{% endblock %}